### PR TITLE
Update Doxygen-generated Documentation

### PR DESCRIPTION
**Pull request by danintel**
Signed-off-by: danintel <daniel.anderson@intel.com>

### CODE REVIEW

**Comment by danintel** [comment]
This uploads automatically generated documentation from Doxygen to the new Avalon documentation website at https://hyperledger.github.io/avalon/ 

I need 1 approval.

**Comment by manojgop** [comment]
> This uploads automatically generated documentation from Doxygen to the new Avalon documentation website at https://hyperledger.github.io/avalon/
> 
> I need 1 approval.

@danintel Why do we need to add all doxygen generated documentation in github. Can we build and generate these temporary files and keep it outside github that could be referred by  https://hyperledger.github.io/avalon/

**Comment by danintel** [comment]
@manojgop If you know of a better hosting website, let me know. Ry Jones of Hyperledger suggested having it at hyperledger.github.io . I do not see any disadvantages of having it at hyperledger.github.io.

**Comment by manojgop** [comment]
> @manojgop If you know of a better hosting website, let me know. Ry Jones of Hyperledger suggested having it at hyperledger.github.io . I do not see any disadvantages of having it at hyperledger.github.io.

I'm fine with this hosting website. I was thinking would it be better to generate the doxygen files in hosting webserver rather than keeping it in github. Or is keeping auto generated doxygen files in github a better approach ?

**Pull request closed without merging**
