### PR TITLE
Documentation Changes

### PR DESCRIPTION
**Pull request by danintel**
-Point to New Hyperledger Avalon Documentation Website

https://hyperledger.github.io/avalon/

This is populated from the `gh-pages` branch of the Avalon repo:
    https://github.com/hyperledger/avalon/tree/gh-pages
This branch is created from Doxygen-generated source built in `docs/Makefile` .

-Add URLs for Avalon Listener, LMDB, and ZMQ

Signed-off-by: danintel <daniel.anderson@intel.com>

### CODE REVIEW

**Comment by manojgop** [comment]
@danintel . This looks nice. Do we need to add all doxygen generated files in github. I can see lot of files in https://github.com/hyperledger/avalon/tree/gh-pages

**Comment by danintel** [comment]
Yes. Doxygen generates a lot of files, one per object I think. The more documentation the better I think--these files are not visible from the hyperledger.github.io website.

**Comment by manojgop** [comment]
> hyperledger.github.io

Is there a way to keep auto generated doxygen files in webserver of hyperledger.github.io.  Do we really need to check in the generated files in https://github.com/hyperledger/avalon/tree/gh-pages ? If we keep doxygen generated files in git then do we need to checkout and merge these files every time docs are built ?

**Comment by danintel** [comment]
Yes. To update the documentation we need to regenerate the Doxygen files, then commit and push the changes.  I plan on doing this at release time, not at every commit.

Ry said this can all be automated in Jenkins, if we need to do that.

**Comment by manojgop** [comment]
> Yes. To update the documentation we need to regenerate the Doxygen files, then commit and push the changes. I plan on doing this at release time, not at every commit.
> 
> Ry said this can all be automated in Jenkins, if we need to do that.

Ok. Then it looks good

**Comment by danintel** [comment]
@manojgop Could you approve it then?
> Ok. Then it looks good

**Pull request merged**
